name: gg_args
description: Additions and helpers to the args packages needed by various of our projects.
version: 2.0.5
repository: https://github.com/inlavigo/gg_args.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  gg_capture_print: ^1.0.1
  gg_console_colors: ^2.0.0
  gg_log: ^1.0.0
  matcher: ^0.12.16+1
  meta: ^1.11.0
  mocktail: ^1.0.3
  path: ^1.8.0
  recase: ^4.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0