name: gg_args
description: Additions and helpers to the args packages needed by various of our projects.
version: 1.0.8
repository: https://github.com/inlavigo/gg_args.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  colorize: ^3.0.0
  gg_capture_print: ^1.0.1
  meta: ^1.12.0
  path: ^1.8.0
  recase: ^4.1.0

dev_dependencies:
  gg_check: ^1.0.2
  lints: ^3.0.0
  pana: ^0.22.1
  test: ^1.24.0
